name: OpenAPI Change Checker

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  check-openapi-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: willsfidell/openapi_change_checker@v0.1
